# -*- coding: utf-8 -*-
"""Assignment1_NeuralNetworks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JpmtgFUWkvjb2CL7imjLv5b31WZNv6pt

# Assignment 1: Neural Networks
## IMDB Movie Review Classification
"""

# Import required libraries
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib.pyplot as plt

# Load the IMDB movie review dataset
from tensorflow.keras.datasets import imdb

(train_data, train_labels), (test_data, test_labels) = imdb.load_data(
    num_words=10000)

print("Number of training samples:", len(train_data))
print("Number of test samples:", len(test_data))

print("\nFirst training review:")
print(train_data[0])

print("\nLabel of first training review:")
print(train_labels[0])

"""## 1. Data Preparation"""

# Convert the reviews into 10,000-dimensional binary vectors
def vectorize_sequences(sequences, dimension=10000):
    results = np.zeros((len(sequences), dimension))
    for i, sequence in enumerate(sequences):
        results[i, sequence] = 1.0
    return results

# Vectorize training and test data
x_train = vectorize_sequences(train_data)
x_test = vectorize_sequences(test_data)

# Convert labels to floating-point values
y_train = np.asarray(train_labels).astype("float32")
y_test = np.asarray(test_labels).astype("float32")

# Check the resulting shapes
print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# Create a validation set using the first 10,000 training samples
x_val = x_train[:10000]
partial_x_train = x_train[10000:]

y_val = y_train[:10000]
partial_y_train = y_train[10000:]

# Check the sizes
print("Training samples:", partial_x_train.shape)
print("Validation samples:", x_val.shape)
print("Test samples:", x_test.shape)

"""## 2. Baseline Model"""

# Build the baseline neural network
model_baseline = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

# Compile the model
model_baseline.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

# Display the model architecture
model_baseline.summary()

# Train the baseline model for 20 epochs
history_baseline = model_baseline.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Extract training history
history_dict = history_baseline.history

accuracy = history_dict["accuracy"]
val_accuracy = history_dict["val_accuracy"]
loss = history_dict["loss"]
val_loss = history_dict["val_loss"]

epochs = range(1, len(accuracy) + 1)

# Plot training and validation accuracy
plt.figure(figsize=(8, 5))
plt.plot(epochs, accuracy, "o-", label="Training Accuracy")
plt.plot(epochs, val_accuracy, "o-", label="Validation Accuracy")
plt.title("Baseline Model: Training and Validation Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.show()

# Plot training and validation loss
plt.figure(figsize=(8, 5))
plt.plot(epochs, loss, "o-", label="Training Loss")
plt.plot(epochs, val_loss, "o-", label="Validation Loss")
plt.title("Baseline Model: Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.show()

# Find the epoch with the highest validation accuracy
best_epoch_acc = np.argmax(val_accuracy) + 1
best_val_acc = np.max(val_accuracy)

# Find the epoch with the lowest validation loss
best_epoch_loss = np.argmin(val_loss) + 1
best_val_loss = np.min(val_loss)

print("Best validation accuracy:")
print(f"Epoch {best_epoch_acc}: {best_val_acc:.4f} ({best_val_acc*100:.2f}%)")

print("\nLowest validation loss:")
print(f"Epoch {best_epoch_loss}: {best_val_loss:.4f}")

"""## 3. Effect of Number of Hidden Layers"""

# Model with ONE hidden layer
model_1layer = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

model_1layer.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_1layer.summary()

# Train the model with ONE hidden layer
history_1layer = model_1layer.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the one-hidden-layer model
val_accuracy_1layer = history_1layer.history["val_accuracy"]
val_loss_1layer = history_1layer.history["val_loss"]

best_epoch_1layer = np.argmax(val_accuracy_1layer) + 1
best_val_acc_1layer = np.max(val_accuracy_1layer)

best_loss_epoch_1layer = np.argmin(val_loss_1layer) + 1
best_val_loss_1layer = np.min(val_loss_1layer)

print("ONE hidden layer model")
print(f"Best validation accuracy: {best_val_acc_1layer:.4f} "
      f"({best_val_acc_1layer*100:.2f}%) at epoch {best_epoch_1layer}")

print(f"Lowest validation loss: {best_val_loss_1layer:.4f} "
      f"at epoch {best_loss_epoch_1layer}")

# Model with THREE hidden layers
model_3layer = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

model_3layer.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_3layer.summary()

# Train the model with THREE hidden layers
history_3layer = model_3layer.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the three-hidden-layer model
val_accuracy_3layer = history_3layer.history["val_accuracy"]
val_loss_3layer = history_3layer.history["val_loss"]

best_epoch_3layer = np.argmax(val_accuracy_3layer) + 1
best_val_acc_3layer = np.max(val_accuracy_3layer)

best_loss_epoch_3layer = np.argmin(val_loss_3layer) + 1
best_val_loss_3layer = np.min(val_loss_3layer)

print("THREE hidden layer model")
print(f"Best validation accuracy: {best_val_acc_3layer:.4f} "
      f"({best_val_acc_3layer*100:.2f}%) at epoch {best_epoch_3layer}")

print(f"Lowest validation loss: {best_val_loss_3layer:.4f} "
      f"at epoch {best_loss_epoch_3layer}")

# Compare validation accuracy for 1, 2, and 3 hidden layers

layer_names = ["1 Hidden Layer", "2 Hidden Layers", "3 Hidden Layers"]

layer_accuracies = [
    best_val_acc_1layer * 100,
    best_val_acc * 100,
    best_val_acc_3layer * 100]

plt.figure(figsize=(8, 5))
bars = plt.bar(layer_names, layer_accuracies)

plt.title("Effect of Number of Hidden Layers on Validation Accuracy")
plt.xlabel("Network Architecture")
plt.ylabel("Best Validation Accuracy (%)")
plt.ylim(85, 90)

# Add accuracy values above bars
for bar, value in zip(bars, layer_accuracies):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        value + 0.05,
        f"{value:.2f}%",
        ha="center")

plt.show()

"""## 4. Effect of Number of Hidden Units"""

# Model with TWO hidden layers and 8 units per layer
model_8units = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(8, activation="relu"),
    keras.layers.Dense(8, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

model_8units.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_8units.summary()

# Train the model with 8 units per hidden layer
history_8units = model_8units.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the 8-unit model
val_accuracy_8units = history_8units.history["val_accuracy"]
val_loss_8units = history_8units.history["val_loss"]

best_epoch_8units = np.argmax(val_accuracy_8units) + 1
best_val_acc_8units = np.max(val_accuracy_8units)

best_loss_epoch_8units = np.argmin(val_loss_8units) + 1
best_val_loss_8units = np.min(val_loss_8units)

print("8-unit model")
print(f"Best validation accuracy: {best_val_acc_8units:.4f} "
      f"({best_val_acc_8units*100:.2f}%) at epoch {best_epoch_8units}")

print(f"Lowest validation loss: {best_val_loss_8units:.4f} "
      f"at epoch {best_loss_epoch_8units}")

# Model with TWO hidden layers and 32 units per layer
model_32units = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(32, activation="relu"),
    keras.layers.Dense(32, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

model_32units.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_32units.summary()

# Train the model with 32 units per hidden layer
history_32units = model_32units.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the 32-unit model
val_accuracy_32units = history_32units.history["val_accuracy"]
val_loss_32units = history_32units.history["val_loss"]

best_epoch_32units = np.argmax(val_accuracy_32units) + 1
best_val_acc_32units = np.max(val_accuracy_32units)

best_loss_epoch_32units = np.argmin(val_loss_32units) + 1
best_val_loss_32units = np.min(val_loss_32units)

print("32-unit model")
print(f"Best validation accuracy: {best_val_acc_32units:.4f} "
      f"({best_val_acc_32units*100:.2f}%) at epoch {best_epoch_32units}")

print(f"Lowest validation loss: {best_val_loss_32units:.4f} "
      f"at epoch {best_loss_epoch_32units}")

# Model with TWO hidden layers and 64 units per layer
model_64units = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dense(64, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

model_64units.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_64units.summary()

# Train the model with 64 units per hidden layer
history_64units = model_64units.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the 64-unit model
val_accuracy_64units = history_64units.history["val_accuracy"]
val_loss_64units = history_64units.history["val_loss"]

best_epoch_64units = np.argmax(val_accuracy_64units) + 1
best_val_acc_64units = np.max(val_accuracy_64units)

best_loss_epoch_64units = np.argmin(val_loss_64units) + 1
best_val_loss_64units = np.min(val_loss_64units)

print("64-unit model")
print(f"Best validation accuracy: {best_val_acc_64units:.4f} "
      f"({best_val_acc_64units*100:.2f}%) at epoch {best_epoch_64units}")

print(f"Lowest validation loss: {best_val_loss_64units:.4f} "
      f"at epoch {best_loss_epoch_64units}")

# Compare the effect of hidden units on validation accuracy

unit_labels = ["8", "16", "32", "64"]

unit_accuracies = [
    best_val_acc_8units * 100,
    best_val_acc * 100,
    best_val_acc_32units * 100,
    best_val_acc_64units * 100
]

plt.figure(figsize=(8, 5))
plt.plot(unit_labels, unit_accuracies, marker="o")

plt.title("Effect of Hidden Units on Validation Accuracy")
plt.xlabel("Units per Hidden Layer")
plt.ylabel("Best Validation Accuracy (%)")
plt.ylim(87.5, 89.5)
plt.grid(True)

for x, y in zip(unit_labels, unit_accuracies):
    plt.text(x, y + 0.05, f"{y:.2f}%", ha="center")

plt.show()

import pandas as pd

units_results = pd.DataFrame({
    "Units per Hidden Layer": [8, 16, 32, 64],
    "Best Validation Accuracy (%)": [
        best_val_acc_8units * 100,
        best_val_acc * 100,
        best_val_acc_32units * 100,
        best_val_acc_64units * 100],
    "Best Accuracy Epoch": [
        best_epoch_8units,
        best_epoch_acc,
        best_epoch_32units,
        best_epoch_64units],
    "Lowest Validation Loss": [
        best_val_loss_8units,
        best_val_loss,
        best_val_loss_32units,
        best_val_loss_64units ]})

units_results.round(4)

"""## 5. Effect of Loss Function"""

# Baseline architecture using MSE loss
model_mse = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dense(1, activation="sigmoid")])

model_mse.compile(
    optimizer="rmsprop",
    loss="mse",
    metrics=["accuracy"])

model_mse.summary()

# Train the model using MSE loss
history_mse = model_mse.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the MSE model
val_accuracy_mse = history_mse.history["val_accuracy"]
val_loss_mse = history_mse.history["val_loss"]

best_epoch_mse = np.argmax(val_accuracy_mse) + 1
best_val_acc_mse = np.max(val_accuracy_mse)

best_loss_epoch_mse = np.argmin(val_loss_mse) + 1
best_val_loss_mse = np.min(val_loss_mse)

print("MSE loss model")
print(f"Best validation accuracy: {best_val_acc_mse:.4f} "
      f"({best_val_acc_mse*100:.2f}%) at epoch {best_epoch_mse}")

print(f"Lowest validation loss: {best_val_loss_mse:.4f} "
      f"at epoch {best_loss_epoch_mse}")

"""## 6. Effect of Activation Function"""

# Baseline architecture using tanh activation
model_tanh = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="tanh"),
    keras.layers.Dense(16, activation="tanh"),
    keras.layers.Dense(1, activation="sigmoid")])

model_tanh.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_tanh.summary()

# Train the model using tanh activation
history_tanh = model_tanh.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the tanh model
val_accuracy_tanh = history_tanh.history["val_accuracy"]
val_loss_tanh = history_tanh.history["val_loss"]

best_epoch_tanh = np.argmax(val_accuracy_tanh) + 1
best_val_acc_tanh = np.max(val_accuracy_tanh)

best_loss_epoch_tanh = np.argmin(val_loss_tanh) + 1
best_val_loss_tanh = np.min(val_loss_tanh)

print("TANH activation model")
print(f"Best validation accuracy: {best_val_acc_tanh:.4f} "
      f"({best_val_acc_tanh*100:.2f}%) at epoch {best_epoch_tanh}")

print(f"Lowest validation loss: {best_val_loss_tanh:.4f} "
      f"at epoch {best_loss_epoch_tanh}")

"""## 7. Effect of Dropout Regularization"""

# Baseline architecture with dropout regularization
model_dropout = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dropout(0.5),
    keras.layers.Dense(1, activation="sigmoid")])

model_dropout.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_dropout.summary()

# Train the model with dropout
history_dropout = model_dropout.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

# Get validation results for the dropout model
val_accuracy_dropout = history_dropout.history["val_accuracy"]
val_loss_dropout = history_dropout.history["val_loss"]

best_epoch_dropout = np.argmax(val_accuracy_dropout) + 1
best_val_acc_dropout = np.max(val_accuracy_dropout)

best_loss_epoch_dropout = np.argmin(val_loss_dropout) + 1
best_val_loss_dropout = np.min(val_loss_dropout)

print("DROPOUT model")
print(f"Best validation accuracy: {best_val_acc_dropout:.4f} "
      f"({best_val_acc_dropout*100:.2f}%) at epoch {best_epoch_dropout}")

print(f"Lowest validation loss: {best_val_loss_dropout:.4f} "
      f"at epoch {best_loss_epoch_dropout}")

# Baseline architecture with 20% dropout
model_dropout02 = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(16, activation="relu"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation="sigmoid")])

model_dropout02.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_dropout02.summary()

history_dropout02 = model_dropout02.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

val_accuracy_dropout02 = history_dropout02.history["val_accuracy"]
val_loss_dropout02 = history_dropout02.history["val_loss"]

best_epoch_dropout02 = np.argmax(val_accuracy_dropout02) + 1
best_val_acc_dropout02 = np.max(val_accuracy_dropout02)

best_loss_epoch_dropout02 = np.argmin(val_loss_dropout02) + 1
best_val_loss_dropout02 = np.min(val_loss_dropout02)

print("DROPOUT 0.2 model")
print(f"Best validation accuracy: {best_val_acc_dropout02:.4f} "
      f"({best_val_acc_dropout02*100:.2f}%) at epoch {best_epoch_dropout02}")

print(f"Lowest validation loss: {best_val_loss_dropout02:.4f} "
      f"at epoch {best_loss_epoch_dropout02}")

"""## 8. Combined Model"""

# Combined candidate model based on previous experiments
model_combined = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(8, activation="tanh"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(8, activation="tanh"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation="sigmoid")])

model_combined.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

model_combined.summary()

history_combined = model_combined.fit(
    partial_x_train,
    partial_y_train,
    epochs=20,
    batch_size=512,
    validation_data=(x_val, y_val))

val_accuracy_combined = history_combined.history["val_accuracy"]
val_loss_combined = history_combined.history["val_loss"]

best_epoch_combined = np.argmax(val_accuracy_combined) + 1
best_val_acc_combined = np.max(val_accuracy_combined)

best_loss_epoch_combined = np.argmin(val_loss_combined) + 1
best_val_loss_combined = np.min(val_loss_combined)

print("COMBINED candidate model")
print(f"Best validation accuracy: {best_val_acc_combined:.4f} "
      f"({best_val_acc_combined*100:.2f}%) at epoch {best_epoch_combined}")

print(f"Lowest validation loss: {best_val_loss_combined:.4f} "
      f"at epoch {best_loss_epoch_combined}")

"""## 9. Comparison of All Models"""

# Summary of all experiments

results = pd.DataFrame({
    "Model": [
        "Baseline",
        "1 Hidden Layer",
        "3 Hidden Layers",
        "8 Units",
        "32 Units",
        "64 Units",
        "MSE Loss",
        "Tanh Activation",
        "Dropout 0.2",
        "Dropout 0.5",
        "Combined Model"
    ],

    "Hidden Layers": [
        2, 1, 3, 2, 2, 2, 2, 2, 2, 2, 2
    ],

    "Units": [
        "16-16",
        "16",
        "16-16-16",
        "8-8",
        "32-32",
        "64-64",
        "16-16",
        "16-16",
        "16-16",
        "16-16",
        "8-8"
    ],

    "Activation": [
        "ReLU",
        "ReLU",
        "ReLU",
        "ReLU",
        "ReLU",
        "ReLU",
        "ReLU",
        "Tanh",
        "ReLU",
        "ReLU",
        "Tanh"
    ],

    "Loss": [
        "Binary Crossentropy",
        "Binary Crossentropy",
        "Binary Crossentropy",
        "Binary Crossentropy",
        "Binary Crossentropy",
        "Binary Crossentropy",
        "MSE",
        "Binary Crossentropy",
        "Binary Crossentropy",
        "Binary Crossentropy",
        "Binary Crossentropy"
    ],

    "Dropout": [
        0, 0, 0, 0, 0, 0, 0, 0, 0.2, 0.5, 0.2
    ],

    "Best Validation Accuracy (%)": [
        best_val_acc * 100,
        best_val_acc_1layer * 100,
        best_val_acc_3layer * 100,
        best_val_acc_8units * 100,
        best_val_acc_32units * 100,
        best_val_acc_64units * 100,
        best_val_acc_mse * 100,
        best_val_acc_tanh * 100,
        best_val_acc_dropout02 * 100,
        best_val_acc_dropout * 100,
        best_val_acc_combined * 100
    ],

    "Best Accuracy Epoch": [
        best_epoch_acc,
        best_epoch_1layer,
        best_epoch_3layer,
        best_epoch_8units,
        best_epoch_32units,
        best_epoch_64units,
        best_epoch_mse,
        best_epoch_tanh,
        best_epoch_dropout02,
        best_epoch_dropout,
        best_epoch_combined
    ]
})

results.round(2)

# Sort models from highest to lowest validation accuracy
results_sorted = results.sort_values(
    by="Best Validation Accuracy (%)",
    ascending=False
).reset_index(drop=True)

results_sorted.round(2)

"""## 10. Repeated-Seed Analysis"""

# Function to repeat a model using different random seeds

def run_model(units=16, activation="relu", dropout=0.0, seed=1):

    # Set random seed for reproducibility
    keras.utils.set_random_seed(seed)

    model = keras.Sequential([
        keras.layers.Input(shape=(10000,)),
        keras.layers.Dense(units, activation=activation),
        keras.layers.Dropout(dropout),
        keras.layers.Dense(units, activation=activation),
        keras.layers.Dropout(dropout),
        keras.layers.Dense(1, activation="sigmoid")])

    model.compile(
        optimizer="rmsprop",
        loss="binary_crossentropy",
        metrics=["accuracy"])

    history = model.fit(
        partial_x_train,
        partial_y_train,
        epochs=20,
        batch_size=512,
        validation_data=(x_val, y_val),
        verbose=0)

    best_accuracy = max(history.history["val_accuracy"])
    best_epoch = np.argmax(history.history["val_accuracy"]) + 1

    return best_accuracy, best_epoch

seeds = [1, 2, 3]

repeat_results = []

for seed in seeds:

    # Tanh model: 16-16
    acc, epoch = run_model(
        units=16,
        activation="tanh",
        dropout=0.0,
        seed=seed)

    repeat_results.append([
        "Tanh 16-16",
        seed,
        acc * 100,
        epoch])

    # ReLU model: 8-8
    acc, epoch = run_model(
        units=8,
        activation="relu",
        dropout=0.0,
        seed=seed)

    repeat_results.append([
        "ReLU 8-8",
        seed,
        acc * 100,
        epoch])

    # Combined model
    acc, epoch = run_model(
        units=8,
        activation="tanh",
        dropout=0.2,
        seed=seed )

    repeat_results.append([
        "Tanh 8-8 + Dropout 0.2",
        seed,
        acc * 100,
        epoch])

repeat_df = pd.DataFrame(
    repeat_results,
    columns=[
        "Model",
        "Seed",
        "Best Validation Accuracy (%)",
        "Best Epoch" ])

repeat_df.round(2)

summary_repeat = repeat_df.groupby("Model").agg(
    Mean_Validation_Accuracy=("Best Validation Accuracy (%)", "mean"),
    SD_Validation_Accuracy=("Best Validation Accuracy (%)", "std"),
    Mean_Best_Epoch=("Best Epoch", "mean")
).reset_index()

summary_repeat.round(3)

"""## 11. Final Model and Test Evaluation"""

# Set seed for reproducibility
keras.utils.set_random_seed(1)

# Build the selected final model
final_model = keras.Sequential([
    keras.layers.Input(shape=(10000,)),
    keras.layers.Dense(8, activation="tanh"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(8, activation="tanh"),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(1, activation="sigmoid")])

final_model.compile(
    optimizer="rmsprop",
    loss="binary_crossentropy",
    metrics=["accuracy"])

final_model.summary()

# Train the final selected model using all training data
# Five epochs were selected based on validation experiments

history_final = final_model.fit(
    x_train,
    y_train,
    epochs=5,
    batch_size=512,
    verbose=1)

# Evaluate the final model on the untouched test set

test_loss, test_accuracy = final_model.evaluate(
    x_test,
    y_test,
    verbose=0
)

print("FINAL TEST RESULTS")
print(f"Test accuracy: {test_accuracy:.4f} ({test_accuracy*100:.2f}%)")
print(f"Test loss: {test_loss:.4f}")

